Deploy
TupoBanKai/test-guru-js pull request #24
Opened 2022-03-02 16:10 UTC by TupoBanKai

2022-03-03 07:53 UTC, BubuntuClu requested changes

2022-03-03 07:53 UTC, BubuntuClu commented on app/controllers/admin/answers_controller.rb
> +    params.require(:answer).permit(:correct, :flag, find_test.id, find_question.id)
не нужно тут никакие `find_test.id, find_question.id` добавлять. ты создаешь ответ через ассоциацию вопроса. оттуда возьмется id вопроса. а зачем тут тест вообще?

2022-03-03 07:53 UTC, BubuntuClu commented on app/controllers/admin/questions_controller.rb
> -  def destroy
почему нельзя удалить вопрос теперь? надо опставить метод

2022-03-03 07:53 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +    find_test.destroy
было правильно. верни как было

2022-03-03 07:53 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +  before_action :find_test, only: [:show, :start, :update, :edit, :update_inline]
опечатка в названии метода была. надо просто исправить опечатку

2022-03-03 07:53 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    if @test.questions.present?
стоит подумать над таким вопросом, зачем показывать пользователю тесты, которые нельзя проходить? или котоыре не готовы к прохождению?
вот видишь ты 0 вопросов, тыкаешь в прохождение, а тебе говорят нет вопросов. ты подумаешь а зачем тогда показывать?
у теста 1 вопрос. ты нажал. отображается вопрос и в нем нет ответов. зачем такое тоже показывать?

добавь флаг готовности теста к отображению, чтобы автор теста сам решал когда можно показывать тест

2022-03-03 07:53 UTC, BubuntuClu commented on app/mailers/tests_mailer.rb
> +  def created_feedback(feedback)
фидбэк никак не относится к тестам. у него должен быть свой мейлер.

2022-03-03 07:53 UTC, BubuntuClu commented on app/models/test.rb
> +  has_many :users, through: :test_passages, dependent: :destroy
смотри. ты удалил тест, и подразумеваешь что хочешь удалить всех пользователей, которые его проходили? зачем так поступать?

но для таких желающих как ты, опция dependent не работает для ассоциаций с through

2022-03-03 07:53 UTC, BubuntuClu commented on config/routes.rb
> +  resources :feedbacks, only: [:create, :new] do
зачем тут блок `do/end`?

2022-03-03 07:53 UTC, BubuntuClu commented on db/schema.rb
> -  add_foreign_key "answers", "questions"
куда-то подевались все внешние ключи. что с ними стало?

2022-03-03 07:53 UTC, BubuntuClu commented on app/models/answer.rb
> +  validates :flag, presence: true
зачем в ответах нужен этот флаг?

2022-03-03 07:53 UTC, BubuntuClu commented on app/models/answer.rb
>      errors.add(:base) if question.answers.count >= 4
текст к ошибке добавь

2022-03-10 17:46 UTC, TupoBanKai commented on app/models/answer.rb
> +  validates :flag, presence: true
Поле так называется, на самом деле это body. Переименую

2022-03-11 12:56 UTC, merged